import logo from "./assets/robot.png";
import "./App.css";

function App() {
  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        margin: "100px 20px",
      }}
    >
      <img
        src={logo}
        alt="logo"
        style={{ width: "100px", borderRadius: "35px" }}
      />
      <h2>Weird Web</h2>
      <p>
        A simple game where you try to figure out which image is generated by AI
        and which is real.
      </p>
    </div>
  );
}

export default App;
