// const topics = [
//   "phone",
//   "book",
//   "plane",
//   "bicycle",
//   "car",
//   " train",
//   "table",
//   "chair",
//   "computer",
//   "lamp",
//   "desk",
//   "pen",
//   "paper",
//   "house",
//   "dog",
//   "cat",
//   "mouse",
//   "cookie",
//   "glass",
//   "cup",
//   "fork",
//   "spoon",
//   "plate",
//   "bowl",
//   "oven",
//   "stove",
//   " fridge",
//   "laundry",
//   "toothbrush",
//   "television",
//   "game console",
//   "radio",
//   "speakers",
//   "headphones",
//   "keys",
//   "blender",
//   "piano",
//   "guitar",
//   "saxophone",
//   "violin",
//   "banjo",
//   "drum",
//   "monkey",
//   "giraffe",
//   "lion",
//   "tiger",
// ];

const themes = [
  "anime",
  "cartoon",
  "illustration",
  "vector",
  "photo",
  "drawing",
  "painting",
  "digital",
  "art",
  "graphic",
];

export const getTheme = () => {
  // return a random topic
  let theme = themes[Math.floor(Math.random() * themes.length)];
  return theme;
};
